### ISSUE TITLE
Navbar Padding

### ISSUE THREAD

**Issue by cordmata** [gios-asu/ASU-Web-Standards-Bootstrap#85]
Is there a reason that the padding here:

https://github.com/gios-asu/ASU-Web-Standards-Bootstrap/blob/master/scss/_navs.scss#L298

is only applied to the first child?

I'm finding that when the nav is collapsed the other elements don't align correctly.

**Comment by idmontie** [comment]
Yeah, there should be another style in there for

```scss
@media (max-width: $asu-screen-md-max) {
  padding-left: 25px;
}
```

It was an oversite when trying to make sure that we are compliant with the sizes spec'd out on the Hub Web Standards page.
